### PR TITLE
fix: verify payload signature on v2 messages

### LINKED ISSUE #42: SEC: lack of signature verification on incoming DMs
Description: The Flutter SDK at ae8ec88fc6568d3e96cfa43704d2b68c95601c77 fails to check sender signature validity when receiving a message. This means Flutter will display messages with invalid signatures (but correct encryption) when the xmtp-js SDK would correctly reject these messages.

Flutter [code](https://github.com/xmtp/xmtp-flutter/blob/550b273/lib/src/conversation/conversation_v2.dart#L227) in question, notice lack of signature verification after message decryption. This [check](https://github.com/xmtp/xmtp-js/blob/2d76b45/src/conversations/Conversation.ts#L382) in xmtp-js is what filters these improperly signed messages in the web app.

**Repro Steps**:
- Use patch below to make xmtp-js SDK corrupt message signatures
- Send to a target address
- View messages from recipient address in Flutter example and in XMTP example chat app, sent messages should only be displayed in Flutter example. Webapp will show console logs for invalid message signatures.

**Change to xmtp-js to create malicious sender SDK (for repro)**:
```
diff --git a/src/conversations/Conversation.ts b/src/conversations/Conversation.ts
index 45a21c6..d2959e9 100644
--- a/src/conversations/Conversation.ts
+++ b/src/conversations/Conversation.ts
@@ -324,15 +324,17 @@ export class ConversationV2 {
     content: any,
     options?: SendOptions
   ): Promise<MessageV2> {
+    console.log('FAKE_PAYLOAD FAKE_DIGEST')
     const payload = await this.client.encodeContent(content, options)
+    const fakePayload = await this.client.encodeContent("bad signature contents", options)
     const header: message.MessageHeaderV2 = {
       topic: this.topic,
       createdNs: dateToNs(options?.timestamp || new Date()),
     }
     const headerBytes = message.MessageHeaderV2.encode(header).finish()
-    const digest = await sha256(concat(headerBytes, payload))
+    const digest = await sha256(concat(headerBytes, fakePayload))
     const signed = {
-      payload,
+      payload: payload,
       sender: this.client.keys.getPublicKeyBundle(),
       signature: await this.client.keys.getCurrentPreKey().sign(digest),
     }
```

### PR DESCRIPTION
**Pull request by dmccartney**
This fixes #42

### CODE REVIEW

File: lib/src/conversation/conversation_v2.dart [hunk 1]
```diff
@@ -217,14 +222,31 @@ class ConversationManagerV2 {
...
+    // Discard the message if the payload is not properly signed.
+    var digest = await sha256(msg.v2.headerBytes + signed.payload);
+    var signer = ecRecover(
+      Uint8List.fromList(digest),
+      signed.signature.toMsgSignature(),
+    );
+    if (signer.toEthereumAddress() != signed.sender.pre) {
+      debugPrint('discarding message with bad signature');
+      return null;
+    }
```
Comment (dmccartney) [inline lib/src/conversation/conversation_v2.dart:248]: This is the gist of the fix.

File: tool/local-node/docker-compose.yml [hunk 2]
```diff
@@ -1,6 +1,7 @@
 services:
   waku-node:
     image: xmtp/node-go:latest
+    platform: linux/amd64
```
Comment (dmccartney) [inline tool/local-node/docker-compose.yml:4]: For more context see https://github.com/xmtp/xmtp-js/pull/262

Comment (dmccartney) [reply tool/local-node/docker-compose.yml]: I moved this to it's own PR in #44

File: lib/src/conversation/conversation_v2.dart [hunk 3]
```diff
@@ -217,14 +222,31 @@ class ConversationManagerV2 {
...
+  /// It returns `null` when the message could not be decoded.
+  Future<DecodedMessage?> _decodedFromMessage(
     Conversation conversation,
     xmtp.Message msg,
   ) async {
     var signed = await _decryptMessageV2(msg.v2, conversation.invite);
+
+    // Discard the message if the payload is not properly signed.
+    var digest = await sha256(msg.v2.headerBytes + signed.payload);
+    var signer = ecRecover(
```
Comment (michaelx11) [inline lib/src/conversation/conversation_v2.dart:241]: Going to call in another pair of eyes here @jazzz . I think checking `signer.toEthereumAddress() == signed.sender.pre` is sufficient, but it may come down to the details of `ecRecover`. Looking in [web3dart/src/crypto/secp256k1](https://github.com/xclud/web3dart/blob/5e44c3a/lib/src/crypto/secp256k1.dart#L158) it seems like ecRecover will panic on error which should be the desired behavior, as opposed to returning a `0` or something.

**Review by michaelx11 — APPROVED** [review]
LGTM, rechecked it using the test wallet and confirmed the messages are filtered out correctly.

I see a lot of these debug logs which is a good sign.
```
...
flutter: discarding message with bad signature
flutter: discarding message with bad signature
```

File: lib/src/conversation/conversation_v2.dart (hunk 3 above)
Comment (dmccartney) [reply lib/src/conversation/conversation_v2.dart:241]: note in case anyone is still 👀 ing at this: `toEthereumAddress` is our own helper for massaging list-of-bytes-as-public-key into `EthereumAddress` instances that are easier to display / compare: [lib/src/common/signature.dart#L250](https://github.com/xmtp/xmtp-flutter/blob/main/lib/src/common/signature.dart#L250).
