### PR TITLE
fix: pin timestamp on invite to envelope, drop invalid

### LINKED ISSUE #35: Conversations created on flutter sdk are not visible on other clients!
I have created a few new conversations with flutter SDK and those are not visible on xmtp.chat. And when I try to message the same wallet from xmtp.chat, one more new conversation is created. So now I see two convos on the flutter client from the same wallet and one convo on xmtp.chat!

Screenshot 2023-01-09 at 15 18 32

IMG_3146

### PR DESCRIPTION
**Pull request by dmccartney**
This fixes #35 and unifies treatment for invalid envelopes with `xmtp-js`.

The envelope and the invite must have the same timestamp. 

Outgoing: Previously `xmtp-flutter` was constructing invites such that they could differ a bit (it was calling `nowNs()` twice). Now, with this PR, the timestamps are constructed to match.

Incoming: Previously `xmtp-flutter` didn't care if it received an invite with mismatching envelope/invite timestamps. This caused conversations to appear that were discarded by other clients. Now, with this PR, invites with mismatching timestamps are discarded (consistent with `xmtp-js`).

### CODE REVIEW

File: lib/src/conversation/conversation_v2.dart [hunk 1]
```diff
@@ -88,29 +95,55 @@ class ConversationManagerV2 {
...
+  /// Note: bad conversation invitation envelopes are discarded.
   Stream<Conversation> streamConversations() => _api.client
       .subscribe(xmtp.SubscribeRequest(contentTopics: [
         Topic.userInvite(_me.hex),
       ]))
-      .map((e) => xmtp.SealedInvitation.fromBuffer(e.message))
-      .asyncMap((sealed) => _conversationFromInvite(sealed));
+      .asyncMap((e) => _conversationFromEnvelope(e))
+      // Remove nulls (which are discarded bad envelopes).
+      .where((event) => event != null)
```
Comment (neekolas) [inline lib/src/conversation/conversation_v2.dart:119]: `event` seems like odd naming, vs something like `convo`.

File: lib/src/conversation/conversation_v2.dart [hunk 2]
```diff
@@ -130,19 +165,20 @@ class ConversationManagerV2 {
...
+    var signed = await _signContent(auth.keys, header, encoded);
+    var encrypted =
+        await _encryptMessageV2(auth.keys, conversation.invite, header, signed);
     var dm = xmtp.Message(v2: encrypted);
-    await _api.client.publish(xmtp.PublishRequest(envelopes: [
+    await api.client.publish(xmtp.PublishRequest(envelopes: [
       xmtp.Envelope(
         contentTopic: conversation.topic,
-        timestampNs: nowNs(),
+        timestampNs: now,
```
Comment (dmccartney) [inline lib/src/conversation/conversation_v2.dart:181]: the only logic change in this method is using the same `nowNs()` result here in the `Envelope` and the `MessageHeaderV2` above -- the rest of the diff is just name-visibility changes (`_auth` -> `auth`, `_api` -> `api`).

**Review by neekolas — APPROVED** [review]
